### PR TITLE
Better error handling

### PR DESCRIPTION
**Pull request by Skatox**
Hi, this pull request validates that json data received from server exists before setting last error, because in some cases, it doesn't return the xdebug_message, also this code centralizes error handling.

BTW, if this pull is accepted, could you please update composer? We need to have latest commit in composer repo.

### CODE REVIEW

**Comment by vdespa** [comment]
Hi Skatox and thanks for the PR!

I will try to review your code in a timely manner. I am not very happy with the implementation which catches exceptions inside the library. I want to give the user of the library the possibility to catch exceptions. See issue #3.

Any feedback is welcome.

**Comment by Skatox** [comment]
Ok, I agree. It should be better to let the user control the exceptions.

**Comment by vdespa** [comment]
@Skatox I started working in the development branch on a new version of this library.

https://github.com/vdespa/Vtiger-Web-Services-PHP-Client-Library/tree/development

It is a complete redo of the library, still in a very alpha state. It is possible to do CRUD operations on the Account entity.

Feedback is welcomed. Let me know what you think.

**Comment by Skatox** [comment]
Thanks for the info, as soon as I have time, I'll check it.

El 11/15/15 a las 11:41, Valentin Despa escribió:
>
> @Skatox <https://github.com/Skatox> I started working in the
> development branch on a new version of this library.
>
> https://github.com/vdespa/Vtiger-Web-Services-PHP-Client-Library/tree/development
>
> It is a complete redo of the library, still in a very alpha state. It
> is possible to do CRUD operations on the Account entity.
>
> Feedback is welcomed. Let me know what you think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vdespa/Vtiger-Web-Services-PHP-Client-Library/pull/7#issuecomment-156824724>.
>

-- 
Miguel Ángel Useche
migueluseche@skatox.com
http://skatox.com/
@skatox

**Pull request closed without merging**
